seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
exporters:
 - file: ./exporters/convert_json.yaml
   disabled: true
